"""Load the accuracy fixture datasets into a running AsterixDB cluster.

Creates the ``accuracy`` dataverse with one open dataset per fixture file and
inserts every record. Records keep their fields as-is; an autogenerated key is
added so no fixture needs its own primary key.

Run standalone before an accuracy suite (the CI workflow does this) or import
:func:`load_datasets` from a fixture:

    python -m tests.accuracy.fixtures.loader --cc-base-url http://localhost:19002
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import httpx

DATAVERSE = "accuracy"
DATA_DIR = Path(__file__).parent / "data"

# fixture file  ->  dataset name
DATASETS: dict[str, str] = {
    "comics.books.json": "comics_books",
    "comics.characters.json": "comics_characters",
    "mflix.movies.json": "mflix_movies",
    "mflix.shows.json": "mflix_shows",
    "support.tickets.json": "support_tickets",
}

QUERY_SERVICE_PATH = "/query/service"


def _run_statement(client: httpx.Client, cc_base_url: str, statement: str) -> None:
    response = client.post(
        cc_base_url.rstrip("/") + QUERY_SERVICE_PATH,
        data={"statement": statement},
        timeout=120.0,
    )
    response.raise_for_status()
    body = response.json()
    if body.get("status") != "success":
        errors = body.get("errors") or body
        raise RuntimeError(f"AsterixDB statement failed: {errors}")


def _bootstrap_ddl() -> str:
    lines = [
        f"DROP DATAVERSE {DATAVERSE} IF EXISTS;",
        f"CREATE DATAVERSE {DATAVERSE};",
        f"USE {DATAVERSE};",
        "CREATE TYPE DocType AS open { pk: uuid };",
    ]
    for dataset in DATASETS.values():
        lines.append(f"CREATE DATASET {dataset}(DocType) PRIMARY KEY pk AUTOGENERATED;")
    return "\n".join(lines)


def _insert_statement(dataset: str, records: list[dict]) -> str:
    payload = json.dumps(records)
    return f"USE {DATAVERSE};\nINSERT INTO {dataset} ({payload});"


def load_datasets(cc_base_url: str = "http://localhost:19002") -> dict[str, int]:
    """Create the dataverse and load every fixture. Returns dataset -> row count."""
    counts: dict[str, int] = {}
    with httpx.Client() as client:
        _run_statement(client, cc_base_url, _bootstrap_ddl())
        for filename, dataset in DATASETS.items():
            records = json.loads((DATA_DIR / filename).read_text())
            _run_statement(client, cc_base_url, _insert_statement(dataset, records))
            counts[dataset] = len(records)
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description="Load accuracy fixtures into AsterixDB")
    parser.add_argument("--cc-base-url", default="http://localhost:19002")
    args = parser.parse_args()
    counts = load_datasets(args.cc_base_url)
    total = sum(counts.values())
    for dataset, count in counts.items():
        print(f"  {DATAVERSE}.{dataset}: {count} rows")
    print(f"loaded {total} rows across {len(counts)} datasets into '{DATAVERSE}'")


if __name__ == "__main__":
    main()
